# Site settings
title: candycane development blog
email: yandod@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  CakePHP version of Redmine: CandyCane.
  I also started another blog in English.
  海外テックネタ中心の別ブログ、A-Listersも更新中です。あわせてどうぞ。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.candycane.jp" # the base hostname & protocol for your site
twitter_username: yando
github_username:  yandod
timezone: Asia/Tokyo

# Build settings
markdown: kramdown
